import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Codex } from "@openai/codex-sdk";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_AGENT_HOME = path.join(__dirname, "..", "agent-home");

// Hermes-style identity: AGENTS.md is generated from soul + user profile +
// agent memory + harness contract, so every new thread starts with the
// current state of what Clara knows. Clara herself edits USER.md/MEMORY.md
// (workspace-write sandbox scoped to her home directory).
const IDENTITY_FILES = ["SOUL.md", "USER.md", "MEMORY.md", "CONTRACT.md"];

function composeAgentsMd(agentHome) {
  const parts = IDENTITY_FILES.map((name) => {
    try {
      return fs.readFileSync(path.join(agentHome, name), "utf8").trim();
    } catch {
      return "";
    }
  }).filter(Boolean);
  const banner =
    "<!-- Generated by Clara from SOUL.md + USER.md + MEMORY.md + CONTRACT.md. Edit those files, not this one. -->";
  fs.writeFileSync(
    path.join(agentHome, "AGENTS.md"),
    `${banner}\n\n${parts.join("\n\n---\n\n")}\n`
  );
}

// One Codex thread per conversation. Auth comes from ~/.codex/auth.json
// (ChatGPT subscription); config overrides keep Clara from inheriting the
// user's global MCP servers and turn-end notifications.
//
// Each conversation gets its own Codex instance whose `clara` MCP server URL
// carries the conversation id — that is how tool calls (open_url, list_tabs)
// are scoped to the right feed.
export class AgentService {
  constructor({ mcpPort, agentHome = DEFAULT_AGENT_HOME } = {}) {
    this.mcpPort = mcpPort;
    this.agentHome = agentHome;
    this.threads = new Map();
    this.aborts = new Map();
    this.queues = new Map();
    // conversationId -> Codex thread id, for resuming across restarts.
    this.resumeIds = new Map();
  }

  // Register a persisted thread id so the next #thread() resumes it instead
  // of starting fresh (called during session rehydration).
  registerResume(conversationId, threadId) {
    if (threadId) this.resumeIds.set(conversationId, threadId);
  }

  // The live Codex thread id for a conversation, once known (persisted so the
  // conversation resumes after a restart).
  threadId(conversationId) {
    return this.threads.get(conversationId)?.id ?? this.resumeIds.get(conversationId) ?? null;
  }

  #codexFor(conversationId) {
    const config = {
      notify: [],
      mcp_servers: {
        figma: { enabled: false },
        node_repl: { enabled: false },
      },
    };
    if (this.mcpPort) {
      config.mcp_servers.clara = {
        url: `http://127.0.0.1:${this.mcpPort}/mcp/${conversationId}`,
        // Without this, non-interactive exec auto-cancels every MCP tool call
        // (approval elicitations resolve to Cancel when nobody can answer).
        default_tools_approval_mode: "approve",
      };
    }
    return new Codex({ config });
  }

  // Turns on one thread must not overlap (warmup vs. first user message),
  // so every run is chained on a per-conversation queue.
  #enqueue(conversationId, job) {
    const prev = this.queues.get(conversationId) ?? Promise.resolve();
    const next = prev.then(job, job);
    this.queues.set(conversationId, next);
    return next;
  }

  // First turn on a thread pays ~40s of cold start; later turns take ~6s.
  // Warming up as soon as a conversation is created hides that latency.
  warmup(conversationId) {
    const thread = this.#thread(conversationId);
    this.#enqueue(conversationId, () =>
      thread.run("Warmup ping. Reply with exactly: ok").catch(() => {})
    );
  }

  #thread(conversationId) {
    let thread = this.threads.get(conversationId);
    if (!thread) {
      composeAgentsMd(this.agentHome);
      const codex = this.#codexFor(conversationId);
      const options = {
        workingDirectory: this.agentHome,
        skipGitRepoCheck: true,
        // Writable so Clara can update USER.md/MEMORY.md (her own home).
        sandboxMode: "workspace-write",
        approvalPolicy: "never",
        modelReasoningEffort: "low",
      };
      const resumeId = this.resumeIds.get(conversationId);
      thread = resumeId
        ? codex.resumeThread(resumeId, options)
        : codex.startThread(options);
      this.threads.set(conversationId, thread);
    }
    return thread;
  }

  send(conversationId, text, onEvent) {
    const thread = this.#thread(conversationId);
    return this.#enqueue(conversationId, async () => {
      const controller = new AbortController();
      this.aborts.set(conversationId, controller);
      try {
        const { events } = await thread.runStreamed(text, {
          signal: controller.signal,
        });
        for (;;) {
          const { value: event, done } = await events.next();
          if (done) break;
          onEvent(event);
        }
      } catch (err) {
        onEvent({ type: "error", message: String(err?.message ?? err) });
      } finally {
        this.aborts.delete(conversationId);
      }
    });
  }

  abort(conversationId) {
    this.aborts.get(conversationId)?.abort();
  }

  // One-off prompt on a shared utility thread (group summaries etc.).
  // Reuses the normal queue, so calls serialize; returns the final message.
  async summarize(prompt) {
    let text = "";
    await this.send("clara-utility", prompt, (event) => {
      if (event.type === "item.completed" && event.item?.type === "agent_message") {
        text = event.item.text;
      }
    });
    return text;
  }
}
